name: "Fast Mattermost Notifications"
description: "Simple and fast mattermost notifier (running on bash)"
branding:
  icon: "message-circle"
  color: "green"
inputs:
  webhook_url:
    description: "Mattermost webhook url"
    required: true
  message:
    description: "Text that you want to send"
    required: true
  channel:
    description: "Channel to send the message"
    required: false
  username:
    description: "Username from which the message will be sent"
    required: false
runs:
  using: "composite"
  steps:
    - name: Send mattermost notification
      run: ${{ github.action_path }}/notify.sh
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        MESSAGE: ${{ inputs.message }}
        CHANNEL: ${{ inputs.channel }}
        USERNAME: ${{ inputs.username }}
